# Generated by Django 5.0.6 on 2026-06-11 07:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocraticSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("game_sessiya_id", models.IntegerField(blank=True, null=True)),
                ("tur_raqami", models.PositiveSmallIntegerField(default=0)),
                (
                    "stsenariy_tur",
                    models.CharField(default="yolgon_top", max_length=20),
                ),
                ("transkript", models.JSONField(default=list)),
                ("navbat_soni", models.PositiveSmallIntegerField(default=0)),
                ("tugagan", models.BooleanField(default=False)),
                ("yaratilgan", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sokrat_sessiyalar",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-yaratilgan"],
            },
        ),
    ]
