# Generated by Django 5.0.6 on 2026-06-11 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tur", models.PositiveSmallIntegerField(help_text="1-5")),
                (
                    "tur_turi",
                    models.CharField(
                        choices=[
                            ("yolgon_top", "Yolg'onni top"),
                            ("detektiv", "Dalilchi Detektiv"),
                        ],
                        max_length=20,
                    ),
                ),
                ("mazmun", models.JSONField()),
            ],
            options={
                "ordering": ["tur"],
            },
        ),
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("boshlangan", models.DateTimeField(auto_now_add=True)),
                (
                    "holat",
                    models.CharField(
                        choices=[("faol", "Faol"), ("tugagan", "Tugagan")],
                        default="faol",
                        max_length=20,
                    ),
                ),
                ("stsenariy_tartib", models.JSONField(default=list)),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessiyalar",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-boshlangan"],
            },
        ),
        migrations.CreateModel(
            name="GameScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("oyin", models.CharField(default="dalilchi_detektiv", max_length=50)),
                ("ball", models.IntegerField(default=0)),
                ("vaqt", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="natijalar",
                        to="students.student",
                    ),
                ),
                (
                    "sessiya",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yakuniy_natija",
                        to="game.gamesession",
                    ),
                ),
            ],
            options={
                "ordering": ["-vaqt"],
            },
        ),
        migrations.CreateModel(
            name="RoundAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tur_raqami", models.PositiveSmallIntegerField()),
                ("tanlangan_davo", models.CharField(max_length=20)),
                ("tanlangan_dalillar", models.JSONField(default=list)),
                ("tushuntirish", models.TextField(blank=True)),
                ("tanlov_ball", models.IntegerField(default=0)),
                ("dalil_ball", models.IntegerField(default=0)),
                ("tushuntirish_ball", models.IntegerField(default=0)),
                ("jami_ball", models.IntegerField(default=0)),
                ("ai_izoh", models.TextField(blank=True)),
                (
                    "sessiya",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="javoblar",
                        to="game.gamesession",
                    ),
                ),
                (
                    "stsenariy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="javoblar",
                        to="game.gamescenario",
                    ),
                ),
            ],
            options={
                "ordering": ["tur_raqami"],
                "unique_together": {("sessiya", "tur_raqami")},
            },
        ),
    ]
