# Generated by Django 5.0.6 on 2026-06-11 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("emoji", models.CharField(blank=True, max_length=10)),
                ("rang", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.AddField(
            model_name="gamescenario",
            name="fan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stsenariylar",
                to="game.fan",
            ),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="fan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessiyalar",
                to="game.fan",
            ),
        ),
    ]
