# Generated by Django 5.0.6 on 2026-06-11 07:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ism", models.CharField(max_length=120)),
                ("sinf", models.CharField(default="8", max_length=10)),
                (
                    "guruh",
                    models.CharField(
                        choices=[("experimental", "Eksp"), ("control", "Nazorat")],
                        default="experimental",
                        max_length=20,
                    ),
                ),
                (
                    "kirish_kodi",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("yaratilgan", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["yaratilgan"],
            },
        ),
    ]
